version: "3"

services: 

  service1:
    image: service1
    build:
      context: ./service1
      dockerfile: Dockerfile-dev
    container_name: service1
    ports:
      - "4001:80"
    environment:
      - PORT=80
    volumes:
      - /tmp/service1/npm-cache:/root/.npm:z
      - ./service1/src:/usr/app/src:z
    restart: "no"

  service2:
    image: service2
    build:
      context: ./service2
      dockerfile: Dockerfile-dev
    container_name: service2
    ports:
      - "4002:80"
    environment:
      - PORT=80
    volumes:
      - /tmp/service2/npm-cache:/root/.npm:z
      - ./service2/src:/usr/app/src:z
    restart: "no"

  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4000:80"
    depends_on:
      - service1
      - service2
    restart: "no"