name: Push container
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      frontendPath:
        required: true
        type: string
      dockerfileName:
        required: true
        type: string
      baseAddr:
        required: true
        type: string
    secrets:
      DOCKER_REGISTRY:
        required: true      
      DOCKER_USERNAME:
        required: true      
      DOCKER_PASSWORD:
        required: true

jobs:
  push_container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            ${{ inputs.frontendPath }}
      
      - name: copy environment file
        working-directory: ${{ github.workspace }}/${{ inputs.frontendPath }}
        run: |
          cat << EOF > .env
          REACT_APP_BASE_URL1=http://${{ inputs.baseAddr }}
          REACT_APP_BASE_URL2=http://${{ inputs.baseAddr }}
          EOF

      - name: docker login
        uses: docker/login-actions@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: build docker image
        working-directory: ${{ github.workspace }}/${{ inputs.frontendPath }}
        run: |
          docker build -t \
          ${{ secrets.DOCKER_REGISTRY }}/\
          ${{ inputs.frontendPath }}:\
          ${{ inputs.tag }} \
          --file ${{ inputs.dockerfileName }} \
          .
      
      - name: Scan image trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_REGISTRY }}/${{ inputs.frontendPath }}:${{ inputs.tag }}
          format: sarif
          outputs: trivy_results_${{ inputs.frontendPath }}_${{ inputs.tag }}.sarif
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'

      - name: upload trivy artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy_results_${{ inputs.frontendPath }}_${{ inputs.tag }}
          path: trivy_results_${{ inputs.frontendPath }}_${{ inputs.tag }}.sarif
          retention-days: 4

      - name: push container
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ inputs.frontendPath }}:${{ inputs.tag }}